FROM rust:latest

WORKDIR /app

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./
COPY apps/server/Cargo.toml ./apps/server/Cargo.toml
COPY apps/cli/Cargo.toml ./apps/cli/Cargo.toml
COPY apps/agent/Cargo.toml ./apps/agent/Cargo.toml
COPY crates ./crates

RUN mkdir -p apps/server/src apps/agent/src apps/cli/src && \
    echo "fn main() {}" > apps/server/src/main.rs && \
    echo "fn main() {}" > apps/agent/src/main.rs && \
    echo "fn main() {}" > apps/cli/src/main.rs && \
    cargo build -p itonda-server && \
    rm -rf apps/server/src apps/agent/src apps/cli/src

CMD ["cargo", "watch", "-x", "run --package itonda-server"]
