/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_asset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_media"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["import_media"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/launch/{launch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["launch_media"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Asset: {
            asset_type: components["schemas"]["AssetType"];
            id: string;
        };
        /** @enum {string} */
        AssetType: "poster" | "backdrop" | "logo" | "banner" | "thumbnail" | "icon" | "trailer" | "screenshot";
        CommandResponse: {
            command: string;
            id: string;
            status: components["schemas"]["CommandStatus"];
        };
        /** @enum {string} */
        CommandStatus: "accepted" | "sent";
        JobResponse: {
            job_id: string;
            status: components["schemas"]["JobStatus"];
        };
        /** @enum {string} */
        JobStatus: "queued" | "running" | "completed" | "failed";
        Media: {
            assets: components["schemas"]["Asset"][];
            id: string;
            media_type: string;
            status: components["schemas"]["MediaStatus"];
            title: string;
        };
        MediaImportItem: {
            media_type: components["schemas"]["MediaType"];
            title: string;
        };
        MediaImportPayload: {
            items: components["schemas"]["MediaImportItem"][];
        };
        MediaRefreshPayload: {
            storefront?: null | components["schemas"]["StorefrontId"];
        };
        MediaResponse: {
            items: components["schemas"]["Media"][];
        };
        /** @enum {string} */
        MediaStatus: "not_started" | "in_progress" | "completed" | "abandoned" | "paused";
        /** @enum {string} */
        MediaType: "game" | "movie" | "tv_show";
        /** @enum {string} */
        StorefrontId: "Steam";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_asset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Asset id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_media: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResponse"];
                };
            };
        };
    };
    import_media: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaImportPayload"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
        };
    };
    launch_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Launch profile id */
                launch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaRefreshPayload"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
        };
    };
}
