/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_connected_agents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_asset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_media"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["import_media"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/launch/{launch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["launch_media"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_media_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}/status/{status_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_status"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Agent: {
            agent_version?: string | null;
            /** Format: int64 */
            connected_at?: number | null;
            /** Format: int64 */
            created_at: number;
            hostname?: string | null;
            id: string;
            ip_address?: string | null;
            is_connected: boolean;
            /** Format: int64 */
            last_seen_at?: number | null;
            name: string;
            platform?: string | null;
        };
        Asset: {
            asset_type: components["schemas"]["AssetType"];
            id: string;
        };
        /** @enum {string} */
        AssetType: "poster" | "backdrop" | "logo" | "banner" | "thumbnail" | "icon" | "trailer" | "screenshot";
        CommandResponse: {
            command: string;
            id: string;
            status: components["schemas"]["CommandStatus"];
        };
        /** @enum {string} */
        CommandStatus: "accepted" | "sent";
        GetAgentsResponse: {
            agents: components["schemas"]["Agent"][];
        };
        JobResponse: {
            job_id: string;
            status: components["schemas"]["JobStatus"];
        };
        /** @enum {string} */
        JobStatus: "queued" | "running" | "completed" | "failed";
        Launch: {
            id: string;
            name: string;
        };
        Media: {
            assets: components["schemas"]["Asset"][];
            details?: null | components["schemas"]["MediaDetails"];
            id: string;
            launches: components["schemas"]["Launch"][];
            media_type: components["schemas"]["MediaType"];
            status: components["schemas"]["MediaStatus"];
            title: string;
        };
        MediaDetails: components["schemas"]["MediaGameDetails"];
        MediaGameDetails: {
            /** Format: int64 */
            last_played_at?: number | null;
            /** Format: int64 */
            playtime_minutes?: number | null;
        };
        MediaImportItem: {
            media_type: components["schemas"]["MediaType"];
            title: string;
        };
        MediaImportPayload: {
            items: components["schemas"]["MediaImportItem"][];
        };
        MediaRefreshPayload: {
            storefront?: null | components["schemas"]["StorefrontId"];
        };
        MediaResponse: {
            items: components["schemas"]["Media"][];
            total: number;
            page: number;
            limit: number;
            total_pages: number;
            has_next: boolean;
        };
        MediaSortField: "title" | "last_played_at";
        SortOrder: "asc" | "desc";
        /** @enum {string} */
        MediaStatus: "not_started" | "in_progress" | "completed" | "abandoned" | "paused";
        /** @enum {string} */
        MediaType: "game" | "movie" | "tv_show";
        /** @enum {string} */
        StorefrontId: "Steam";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_connected_agents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAgentsResponse"];
                };
            };
        };
    };
    get_asset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Asset id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_media: {
        parameters: {
            query?: {
                type?: components["schemas"]["MediaType"];
                search?: string;
                status?: components["schemas"]["MediaStatus"];
                storefront?: string;
                sort_by?: components["schemas"]["MediaSortField"];
                sort_order?: components["schemas"]["SortOrder"];
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResponse"];
                };
            };
        };
    };
    import_media: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaImportPayload"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
        };
    };
    launch_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Launch profile id */
                launch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaRefreshPayload"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
        };
    };
    get_media_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
        };
    };
    update_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the media */
                media_id: string;
                /** @description ID of new status */
                status_id: components["schemas"]["MediaStatus"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
